### ISSUE TITLE
files greater than 50mb are not upload and reporting an 404 not found error

### ISSUE THREAD

**Issue by Vaseem88** [lian-yue/vue-upload-component#325]
@lian-yue  when I upload files it is working fine for files with lesser size but with files greater than 50mb do not upload and reporting a 404 not found error, could you please look into this and let me know what is the problem

**Comment by josec89** [comment]
@Vaseem88 that seems to be a problem in the BE where you are trying to upload the file, can you check that you don't have any size limit there?

**Comment by Vaseem88** [comment]
@josec89 Thanks for the information, I looked into my ASP.NET core application and IIS had the default Body request size to be 28MB, Configuring the IIS let the file upload functionality works as expected.
So I am closing this issue.

**Comment by lucianobosco** [comment]
I'm facing the same issue, my apache server allows up to 2MB but when a bigger file is added a 404 is returned.
In fact, my `postAction` is `http://mydomain.com/notes/13358/files` but when a non-valid file is attempted to be uploaded, the component takes my page URL as postAction URL instead of the one defined in my child component. Odd
